"""Starlink inter-satellite link analysis tools."""

from starlink_isl.actual_downlink import (
    ActualPass,
    find_visibility_passes,
    geometry_from_ecef_states,
)
from starlink_isl.cfo_compensation import (
    CFOCompensationResult,
    CFOSequenceCompensationResult,
    compensate_cfo,
    compensate_siso_channel_doppler,
    compensate_siso_channel_sequence_doppler,
)
from starlink_isl.channel_grid import (
    OFDMChannelGridAxes,
    OFDMFrequencyAxis,
    OFDMTimeAxis,
    build_ofdm_channel_grid_axes,
    build_ofdm_frequency_axis,
    build_ofdm_time_axis,
    centered_active_subcarrier_indices,
    fftshift_guard_active_subcarrier_indices,
)
from starlink_isl.downlink_dynamics import (
    SPEED_OF_LIGHT_KM_S,
    DownlinkDynamics,
    downlink_dynamics,
)
from starlink_isl.downlink_geometry import (
    DownlinkGeometry,
    VisibilityWindow,
    downlink_geometry,
    visibility_window,
)
from starlink_isl.ideal_orbit import (
    IdealOrbitConfig,
    KinematicState,
    ground_station_state,
    satellite_state,
)
from starlink_isl.link_budget import (
    BOLTZMANN_J_K,
    REFERENCE_NOISE_TEMPERATURE_K,
    LinkBudgetConfig,
    LinkBudgetResult,
    equivalent_receiver_noise_temperature_k,
    free_space_path_loss_db,
    link_budget,
    system_noise_temperature_k,
    thermal_noise_power_dbw,
)
from starlink_isl.ofdm_channel import (
    SISOChannelGrid,
    SynchronizedSISOChannelGrid,
    evaluate_siso_ofdm_channel_grid,
    predict_block_start_delay_and_doppler_phase,
    save_siso_channel_grid_npz,
    save_synchronized_siso_channel_grid_npz,
    synchronize_siso_ofdm_channel_grid,
    synchronize_siso_ofdm_channel_grid_from_block_start,
)
from starlink_isl.sgp4_orbit import (
    GroundStation,
    SGP4PropagationError,
    ecef_to_geodetic,
    geodetic_to_ecef,
    propagate_ecef,
    propagate_teme,
    satrec_from_omm,
)
from starlink_isl.qpsk import (
    PilotQPSKSnapshot,
    QPSKSnapshot,
    error_vector_magnitude_percent,
    estimate_pilot_frequency_and_phase,
    qpsk_demodulate,
    qpsk_modulate,
    simulate_qpsk_snapshot,
    simulate_pilot_aided_qpsk_snapshot,
    theoretical_qpsk_ber_awgn,
)
from starlink_isl.receiver_filter import (
    ReceiverFilterConfig,
    ReceiverFilterResult,
    apply_receiver_filter,
    design_receiver_filter,
)
from starlink_isl.research_config import (
    ChannelGridBaseline,
    ChannelStateSampling,
    OFDMNumerology,
    OFDMPilotLayout,
    ResearchBaselineConfig,
    load_research_baseline,
)
from starlink_isl.si_interface import (
    DownlinkStateSI,
    downlink_state_si,
    ideal_downlink_state_si,
    sgp4_downlink_state_si,
)
from starlink_isl.state_resampling import (
    StateResamplingError,
    compare_downlink_states,
    resample_downlink_state_si,
)
from starlink_isl.satellite_channel import (
    SISOChannelConfig,
    SISOChannelResult,
    SISOChannelSequenceResult,
    apply_siso_downlink_channel,
    apply_siso_downlink_sequence,
)

__version__ = "0.1.0"

__all__ = [
    "ActualPass",
    "CFOCompensationResult",
    "CFOSequenceCompensationResult",
    "ChannelGridBaseline",
    "ChannelStateSampling",
    "DownlinkDynamics",
    "DownlinkGeometry",
    "DownlinkStateSI",
    "IdealOrbitConfig",
    "KinematicState",
    "LinkBudgetConfig",
    "LinkBudgetResult",
    "OFDMNumerology",
    "OFDMPilotLayout",
    "OFDMChannelGridAxes",
    "OFDMFrequencyAxis",
    "OFDMTimeAxis",
    "PilotQPSKSnapshot",
    "QPSKSnapshot",
    "ReceiverFilterConfig",
    "ReceiverFilterResult",
    "ResearchBaselineConfig",
    "GroundStation",
    "SGP4PropagationError",
    "SISOChannelConfig",
    "SISOChannelGrid",
    "SynchronizedSISOChannelGrid",
    "SISOChannelResult",
    "SISOChannelSequenceResult",
    "StateResamplingError",
    "ecef_to_geodetic",
    "BOLTZMANN_J_K",
    "REFERENCE_NOISE_TEMPERATURE_K",
    "SPEED_OF_LIGHT_KM_S",
    "VisibilityWindow",
    "apply_receiver_filter",
    "build_ofdm_channel_grid_axes",
    "build_ofdm_frequency_axis",
    "build_ofdm_time_axis",
    "centered_active_subcarrier_indices",
    "fftshift_guard_active_subcarrier_indices",
    "compensate_cfo",
    "compensate_siso_channel_doppler",
    "compensate_siso_channel_sequence_doppler",
    "compare_downlink_states",
    "downlink_dynamics",
    "downlink_geometry",
    "downlink_state_si",
    "design_receiver_filter",
    "apply_siso_downlink_channel",
    "apply_siso_downlink_sequence",
    "error_vector_magnitude_percent",
    "evaluate_siso_ofdm_channel_grid",
    "estimate_pilot_frequency_and_phase",
    "equivalent_receiver_noise_temperature_k",
    "free_space_path_loss_db",
    "find_visibility_passes",
    "geodetic_to_ecef",
    "geometry_from_ecef_states",
    "ground_station_state",
    "ideal_downlink_state_si",
    "link_budget",
    "load_research_baseline",
    "propagate_ecef",
    "propagate_teme",
    "predict_block_start_delay_and_doppler_phase",
    "qpsk_demodulate",
    "qpsk_modulate",
    "resample_downlink_state_si",
    "satellite_state",
    "satrec_from_omm",
    "save_siso_channel_grid_npz",
    "save_synchronized_siso_channel_grid_npz",
    "simulate_qpsk_snapshot",
    "simulate_pilot_aided_qpsk_snapshot",
    "synchronize_siso_ofdm_channel_grid",
    "synchronize_siso_ofdm_channel_grid_from_block_start",
    "sgp4_downlink_state_si",
    "system_noise_temperature_k",
    "thermal_noise_power_dbw",
    "theoretical_qpsk_ber_awgn",
    "visibility_window",
]
